services:
  app:
    container_name: ${CONTAINER_NAME:-napcat-message-archiver}
    image: sliots/napcat-message-archiver:${IMAGE_TAG:-latest}
    hostname: ${HOSTNAME:-hostname}
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - WS_URL=${WS_URL}
    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}
    extra_hosts:
      - host.docker.internal:host-gateway
